back/urls.py
from django.urls import path, include
from back.forms import (
    AboutForm,
    BlogForm,
    CourseForm,
    EventForm,
    FunFactForm,
    InterestForm,
    NoticeForm,
    RequirementForm,
    ResearchForm,
    ScholarshipForm,
    SchoolForm,
    TeacherForm
)

from core.models import (
    About,
    Blog,
    Course,
    Event,
    FunFact,
    Interest,
    Notice,
    Requirement,
    Research,
    Scholarship,
    School,
    Teacher
)

from .views import (
    home,
    CustomCreate,
    CustomDetail,
    # about, 
    # blog, 
    # course, 
    # event,
    # notice, 
    # research, 
    # scholarship, 
    # teacher,
)

li0 = [
    'about',
    'blog',
    'course',
    'event',
    'funfact',
    'interest',
    'notice',
    'requirement',
    'research',
    'scholarship',
    'school',
    'teacher'
]


li1 = [
    About,
    Blog,
    Course,
    Event,
    FunFact,
    Interest,
    Notice,
    Requirement,
    Research,
    Scholarship,
    School,
    Teacher
]

li2 = [
    AboutForm,
    BlogForm,
    CourseForm,
    EventForm,
    FunFactForm,
    InterestForm,
    NoticeForm,
    RequirementForm,
    ResearchForm,
    ScholarshipForm,
    SchoolForm,
    TeacherForm
]


# li3 = [
#     'be/about.html',
#     'be/blog.html',
#     'be/course.html',
#     'be/event.html',
#     'be/funfact.html',
#     'be/interest.html',
#     'be/notice.html',
#     'be/requirement.html',
#     'be/research.html',
#     'be/scholarship.html',
#     'be/school.html',
#     'be/teacher.html'
# ]

length = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

app_name = 'backend'


urlpatterns = [
    path('', home, name='home'),
    path('account/', include('login.urls', namespace='b-account'))
    # path('about/', about, name='about'),
    # path(
    #     'about/',
    #     CustomCreate.as_view(
    #         model = li1[0],
    #         form_class = li2[0],
    #         template_name = li3[0]
    #     ),
    #     name = 'about'
    # ),

    # path('blog', blog, name='blog'),
    # # path(

    # # ),

    # path('course/', course, name='course'),
    # path('event/', event, name='event'),
    # path('notice/', notice, name='notice'),
    # path('research/',research , name='research'),
    # path('scholarship/', scholarship, name='scholarship'),
    # path('teacher/', teacher, name='teacher'),
]

for l in length:
    urlpatterns.append(
        path(
                f"{li0[l]}/",
                CustomCreate.as_view(
                    model = li1[l],
                    form_class = li2[l],
                    template_name = f"core/{li0[l]}.html", 
                    success_url = f"#",
                ),
                name = f"{li0[l]}"
            )
    ),
    urlpatterns.append(
        path(
                f"{li0[l]}/<int:id>/",
                CustomDetail.as_view(
                    model = li1[l],
                    template_name = f"core/{li0[l]}-single.html", 
                ),
                name = f"{li0[l]}"
            )
    )

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('', include(('main.urls'), namespace='main')),
    path('admin/', admin.site.urls), 
    path('', include(('core.urls'), namespace='user')),    
    path('be/', include(('back.urls'), namespace='backend')),
    path('account/', include('login.urls', namespace='m-account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.models import (
    Blog,
    Course,
    Event,
    Notice,
    Research,
    Scholarship,
    Teacher
)
from .views import (
    about_view, 
    # blog_view, 
    # teacher_view, 
    contact_view,
    # course_view, 
    home_view, 
    # notice_view, 
    # event_view, 
    # research_view, 
    # scholarship_view,
    CustomList,
    CustomDetail
)

app_name = "user"
# from .views import home_view

li1 = [
    Blog,
    Course,
    Event,
    Notice,
    Research,
    Scholarship,
    Teacher,
]

li2 = [
    'blog',
    'course',
    'event',
    'notice',
    'research',
    'scholarship',
    'teacher',
]

length = [0, 1, 2, 3, 4, 5, 6]
length1 = [0, 1, 2, 3, 6]

urlpatterns = [
        path('', home_view, name='home'),
        path('about/', about_view, name='about'),
        path('account/', include('login.urls', namespace='u-account')),
        path('contact/account/', include('login.urls', namespace='ac-account')),
        path('about/account/', include('login.urls', namespace='ab-account')),
        path('contact/', contact_view, {'li':'contact.html'}, name='contact' ),

        # path('blog-single/<int:pk>', blog_view, {'li':'blog-single.html'}, name='blog-single' ),
        # path('blog/', blog_view, {'li':'blog.html'}, name='blog' ),
        
        # path('teacher-single/<int:pk>', teacher_view, {'li':'teacher-single.html'}, name='teacher-single' ),
        # path('teacher/', teacher_view, {'li':'teacher.html'}, name='teacher' ),
        
        # path('notice-single/', notice_view, {'li':'notice-single.html'}, name='notice-single' ),
        # path('notice/', notice_view, {'li':'notice.html'}, name='notice' ),
        
        # path('course-single/<int:pk>', course_view, {'li':'course-single.html'}, name='course-single' ),
        # path('courses/', course_view, {'li':'courses.html'}, name='courses' ),
        
        # path('event-single/<int:pk>', event_view, {'li':'event-single.html'}, name='event-single' ),
        # path('events/', event_view, {'li':'events.html'}, name='events' ),

        # path('research/', research_view, {'li':'research.html'}, name='research' ),
        # path('scholarship/', scholarship_view, {'li':'scholarship.html'}, name='scholarship' ),

        # path(
        #     'teacher/', 
        #     CustomList.as_view(
        #         model = Teacher,
        #         template_name = 'core/teacher.html'
        #     ), 
        #     name = 'teacher'
        # ),
        # path(
        #     'teacher-single/<int:pk>',
        #     CustomDetail.as_view(
        #         model = Teacher,
        #         template_name = 'core/teacher-single.html'
        #     ),
        #     name = 'teacher-single'
        # ),
    ]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

for i in length :
    urlpatterns.append(
        path(
            li2[i]+'/', 
            CustomList.as_view(
                model = li1[i],
                template_name = 'core/'+li2[i]+'.html'
            ), 
            name = li2[i]
        )      
    )

for n in length1:
    urlpatterns.append(
        path(
            li2[n]+'-single/<int:pk>',
            CustomDetail.as_view(
                model = li1[n],
                template_name = 'core/'+li2[n]+'-single.html'
            ),
            name = li2[n]+'-single'
        )
    )

templates/be/about.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <head>
        <meta charset="utf-8">
        <title>Educenter</title>
    
        <!-- mobile responsive meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
        <!-- ** Plugins Needed for the Project ** -->
        <!-- Bootstrap -->
        <link rel="stylesheet" href=" {% static 'plugins/bootstrap/bootstrap.min.css' %} ">
        <!-- slick slider -->
        <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
        <!-- themefy-icon -->
        <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">
        <!-- animation css -->
        <link rel="stylesheet" href="{% static 'plugins/animate/animate.css' %}">
        <!-- aos -->
        <link rel="stylesheet" href="{% static 'plugins/aos/aos.css' %}">
        <!-- venobox popup -->
        <link rel="stylesheet" href="{% static 'plugins/venobox/venobox.css' %}">
    
        <!-- Main Stylesheet -->
        <link href="{% static 'css/back2.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    
        <!--Favicon-->
        <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
        <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    
    </head>
</head>
<body>
{% include "core/common/preloader.html" %}
{% include "be/header.html" %}
{% include "core/base/modal.html" %}
{% include "core/common/title.html" %}
{% block content %}{% endblock content %}
{% include "core/base/footer.html" %}


<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- aos -->
<script src="{% static 'plugins/aos/aos.js' %}"></script>
<!-- venobox popup -->
<script src="{% static 'plugins/venobox/venobox.min.js' %}"></script>
<!-- filter -->
<script src="{% static 'plugins/filterizr/jquery.filterizr.min.js' %}"></script>
<!-- google map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"></script>
<script src="{% static 'plugins/google-map/gmap.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/be/blog.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/course.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/event.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/funfact.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/header.html
{% load static %}
{% block header %}
<header class="fixed-top header">
  <!-- top header -->
  <div class="top-header py-2 bg-white">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-lg-4 text-center text-lg-left">
          <a class="text-color mr-3" href="callto:+443003030266"><strong>CALL</strong> +44 300 303 0266</a>
          <ul class="list-inline d-inline">
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-facebook"></i></a></li>
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-twitter-alt"></i></a></li>
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-linkedin"></i></a></li>
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-instagram"></i></a></li>
          </ul>
        </div>
        <div class="col-lg-8 text-center text-lg-right">
          <ul class="list-inline">
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url 'backend:notice' %}">notice</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url 'backend:research' %}">research</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url 'backend:scholarship' %}">SCHOLARSHIP</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="#" data-toggle="modal" data-target="#loginModal">log</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="#" data-toggle="modal" data-target="#signupModal">register</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- navbar -->
  <div class="navigation w-100">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark p-0">
        <a class="navbar-brand" href="{% url 'user:home' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
        <button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation"
          aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navigation">
          <ul class="navbar-nav ml-auto text-center">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'backend:home' %}">Home</a>
            </li>
            <li class="nav-item @@about">
              <a class="nav-link" href="{% url 'backend:about' %}">About</a>
            </li>
            <li class="nav-item @@courses">
              <a class="nav-link" href="{% url 'backend:course' %}">COURSES</a>
            </li>
            <li class="nav-item @@events">
              <a class="nav-link" href="{% url 'backend:event' %}">EVENTS</a>
            </li>
            <li class="nav-item @@blog">
              <a class="nav-link" href="{% url 'backend:blog' %}">BLOG</a>
            </li>
            <li class="nav-item @@blog">
              <a class="nav-link" href="{% url 'backend:teacher' %}">TEACHERS</a>
            </li>
            <li class="nav-item dropdown view">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Pages
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'backend:interest' %}">Interests</a>
                <a class="dropdown-item" href="{% url 'backend:requirement' %}">Requirements</a>
                <a class="dropdown-item" href="{% url 'backend:school' %} ">Schools</a>
                <a class="dropdown-item" href="{% url 'backend:funfact' %}">Funfacts</a>
                <a class="dropdown-item" href="{% url 'backend:notice' %}">Notice</a>
                <a class="dropdown-item" href="{% url 'backend:research' %}">Research</a>
                <a class="dropdown-item" href="{% url 'backend:scholarship' %}">Scholarship</a>
              </div>
            </li>
            <li class="nav-item @@contact">
              <a class="nav-link" href="{% url 'user:home' %}">USER HOME</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</header>
{% endblock header %}

templates/be/interest.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/notice.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/requirement.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/research.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/scholarship.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/school.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include 'be/form.html' %}
 
{% endblock content %}

templates/be/teacher.html
{% extends 'be/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% include "core/teacher/teacher-list.html" %}
{% include 'be/form.html' %}
 
{% endblock content %}