back/urls.py
from django.urls import path, include
from back.forms import (
    AboutForm,
    BlogForm,
    CourseForm,
    EventForm,
    FunFactForm,
    InterestForm,
    NoticeForm,
    RequirementForm,
    ResearchForm,
    ScholarshipForm,
    SchoolForm,
    TeacherForm
)

from core.models import (
    About,
    Blog,
    Course,
    Event,
    FunFact,
    Interest,
    Notice,
    Requirement,
    Research,
    Scholarship,
    School,
    Teacher
)

from .views import (
    home,
    CustomCreate,
    CustomDetail,
    # about, 
    # blog, 
    # course, 
    # event,
    # notice, 
    # research, 
    # scholarship, 
    # teacher,
)

li0 = [
    'about',
    'blog',
    'course',
    'event',
    'funfact',
    'interest',
    'notice',
    'requirement',
    'research',
    'scholarship',
    'school',
    'teacher'
]


li1 = [
    About,
    Blog,
    Course,
    Event,
    FunFact,
    Interest,
    Notice,
    Requirement,
    Research,
    Scholarship,
    School,
    Teacher
]

li2 = [
    AboutForm,
    BlogForm,
    CourseForm,
    EventForm,
    FunFactForm,
    InterestForm,
    NoticeForm,
    RequirementForm,
    ResearchForm,
    ScholarshipForm,
    SchoolForm,
    TeacherForm
]


# li3 = [
#     'be/about.html',
#     'be/blog.html',
#     'be/course.html',
#     'be/event.html',
#     'be/funfact.html',
#     'be/interest.html',
#     'be/notice.html',
#     'be/requirement.html',
#     'be/research.html',
#     'be/scholarship.html',
#     'be/school.html',
#     'be/teacher.html'
# ]

length = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

app_name = 'backend'


urlpatterns = [
    path('', home, name='home'),
    path('account/', include('login.urls', namespace='b-account'))
    # path('about/', about, name='about'),
    # path(
    #     'about/',
    #     CustomCreate.as_view(
    #         model = li1[0],
    #         form_class = li2[0],
    #         template_name = li3[0]
    #     ),
    #     name = 'about'
    # ),

    # path('blog', blog, name='blog'),
    # # path(

    # # ),

    # path('course/', course, name='course'),
    # path('event/', event, name='event'),
    # path('notice/', notice, name='notice'),
    # path('research/',research , name='research'),
    # path('scholarship/', scholarship, name='scholarship'),
    # path('teacher/', teacher, name='teacher'),
]

for l in length:
    urlpatterns.append(
        path(
                f"{li0[l]}/",
                CustomCreate.as_view(
                    model = li1[l],
                    form_class = li2[l],
                    template_name = f"core/{li0[l]}.html", 
                    success_url = f"#",
                ),
                name = f"{li0[l]}"
            )
    ),
    urlpatterns.append(
        path(
                f"{li0[l]}/<int:id>/",
                CustomDetail.as_view(
                    model = li1[l],
                    template_name = f"core/{li0[l]}-single.html", 
                ),
                name = f"{li0[l]}"
            )
    )

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('', include(('main.urls'), namespace='main')),
    path('admin/', admin.site.urls), 
    path('', include(('core.urls'), namespace='user')),    
    path('be/', include(('back.urls'), namespace='backend')),
    path('account/', include('login.urls', namespace='m-account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.models import (
    Blog,
    Course,
    Event,
    Notice,
    Research,
    Scholarship,
    Teacher
)
from .views import (
    about_view, 
    # blog_view, 
    # teacher_view, 
    contact_view,
    # course_view, 
    home_view, 
    # notice_view, 
    # event_view, 
    # research_view, 
    # scholarship_view,
    CustomList,
    CustomDetail
)

app_name = "user"
# from .views import home_view

li1 = [
    Blog,
    Course,
    Event,
    Notice,
    Research,
    Scholarship,
    Teacher,
]

li2 = [
    'blog',
    'course',
    'event',
    'notice',
    'research',
    'scholarship',
    'teacher',
]

length = [0, 1, 2, 3, 4, 5, 6]
length1 = [0, 1, 2, 3, 6]

urlpatterns = [
        path('', home_view, name='home'),
        path('about/', about_view, name='about'),
        path('account/', include('login.urls', namespace='u-account')),
        path('contact/account/', include('login.urls', namespace='ac-account')),
        path('about/account/', include('login.urls', namespace='ab-account')),
        path('contact/', contact_view, {'li':'contact.html'}, name='contact' ),

        # path('blog-single/<int:pk>', blog_view, {'li':'blog-single.html'}, name='blog-single' ),
        # path('blog/', blog_view, {'li':'blog.html'}, name='blog' ),
        
        # path('teacher-single/<int:pk>', teacher_view, {'li':'teacher-single.html'}, name='teacher-single' ),
        # path('teacher/', teacher_view, {'li':'teacher.html'}, name='teacher' ),
        
        # path('notice-single/', notice_view, {'li':'notice-single.html'}, name='notice-single' ),
        # path('notice/', notice_view, {'li':'notice.html'}, name='notice' ),
        
        # path('course-single/<int:pk>', course_view, {'li':'course-single.html'}, name='course-single' ),
        # path('courses/', course_view, {'li':'courses.html'}, name='courses' ),
        
        # path('event-single/<int:pk>', event_view, {'li':'event-single.html'}, name='event-single' ),
        # path('events/', event_view, {'li':'events.html'}, name='events' ),

        # path('research/', research_view, {'li':'research.html'}, name='research' ),
        # path('scholarship/', scholarship_view, {'li':'scholarship.html'}, name='scholarship' ),

        # path(
        #     'teacher/', 
        #     CustomList.as_view(
        #         model = Teacher,
        #         template_name = 'core/teacher.html'
        #     ), 
        #     name = 'teacher'
        # ),
        # path(
        #     'teacher-single/<int:pk>',
        #     CustomDetail.as_view(
        #         model = Teacher,
        #         template_name = 'core/teacher-single.html'
        #     ),
        #     name = 'teacher-single'
        # ),
    ]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

for i in length :
    urlpatterns.append(
        path(
            li2[i]+'/', 
            CustomList.as_view(
                model = li1[i],
                template_name = 'core/'+li2[i]+'.html'
            ), 
            name = li2[i]
        )      
    )

for n in length1:
    urlpatterns.append(
        path(
            li2[n]+'-single/<int:pk>',
            CustomDetail.as_view(
                model = li1[n],
                template_name = 'core/'+li2[n]+'-single.html'
            ),
            name = li2[n]+'-single'
        )
    )

login/urls.py
from django.urls import path
from .views import login_view, create_view, logout_view, profile_view, profile_edit, EditUser

app_name = 'account'
urlpatterns = [    
    path('login/', login_view, name='login'),
    path('create-user/', create_view, name='create-user'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('edit/<slug:slug>/', EditUser.as_view(), name='edit')
]

core/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.
from django.db import models

class CommonInfo(models.Model):
    name = models.CharField(max_length=100, null=False)
    content = models.TextField(default='')
    header_about = models.ForeignKey('About', null=True, on_delete=models.CASCADE)
    class Meta:
        abstract = True
        ordering = ['id']

    def __str__(self):
        return self.name

class About(CommonInfo):
       header_about = None

class Blog(CommonInfo):
    name = None
    author = models.ForeignKey('Teacher', on_delete=models.SET_NULL, null=True)
    post_date = models.DateField()
    post_read = models.IntegerField()
    post_share = models.IntegerField()
    post_comments = models.IntegerField()
    heading = models.CharField(max_length=255)
    image_url = models.ImageField(upload_to='images/blog/', null=True)
    class Meta:
        ordering = ['heading']
        
    def __str__(self):
        return self.heading

class Course(CommonInfo):
    c_length = models.IntegerField()
    c_duration = models.IntegerField()
    c_requirement = models.ManyToManyField('Requirement')
    c_teacher = models.ForeignKey('Teacher', on_delete=models.SET_NULL, null=True)
    c_school = models.ForeignKey('School', on_delete=models.CASCADE)
    fees = models.FloatField(null=True, blank=True)
    funding = models.TextField(null=True, blank=True) 
    image_url = models.ImageField(upload_to='images/courses/', null=True)

class Event(CommonInfo):
    location = models.CharField(max_length=255)
    event_date = models.DateField()
    event_time = models.TimeField()
    e_speaker = models.ManyToManyField('Teacher')
    fee = models.IntegerField()
    image_url = models.ImageField(upload_to='images/events/', null=True)

class FunFact(CommonInfo):
    content = None
    number = models.IntegerField()

class Interest(CommonInfo):
    content = None

class Notice(CommonInfo):
    notice_date = models.DateField()

class Requirement(CommonInfo):
    content = None

class Research(CommonInfo):
    image_url = models.ImageField(upload_to='images/research/', null=True)

class School(CommonInfo):
    content = None
    header_about = None

class Scholarship(CommonInfo):
    content = None
    s_course = models.ForeignKey('School', null=True, on_delete=models.CASCADE)
    s_requirement = models.ManyToManyField('Requirement')
    image_url = models.ImageField(upload_to='images/scholarship/', null=True)

class Teacher(CommonInfo):
    education = models.CharField(max_length=255)
    summary = models.CharField(max_length=255)
    t_interest = models.ManyToManyField('Interest')
    email = models.EmailField(default='default@ex.co.ke')
    phone = models.CharField(max_length=50, default='+254 700 000 000')
    social_media = models.CharField(max_length=50, default='default')
    address = models.CharField(max_length=100, default='Default, Setting')
    t_courses = models.ManyToManyField('Course')
    image_url = models.ImageField(upload_to='images/teachers/', null=True)

core/views.py
from django import views
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
from datetime import date
from django.db.models import Q
from django.views.generic import (
    ListView, 
    DetailView
)
from core.models import (
    About,
    Blog, 
    Course,  
    Event,
    FunFact, 
    Notice, 
    Research, 
    Scholarship,
    Teacher 
)


"""------------------------------------------------------------

                    FUNCTION BASED VIEWS
                    
------------------------------------------------------------"""

def base_view(request):
    title = About.objects.get(id=2)
    return title

def home_view(request):
    course_list = Course.objects.filter(id__lt=7)
    course_detail = get_object_or_404(course_list, pk=1)
    teacher_list = Teacher.objects.filter(id__lt=4)
    teacher_detail = get_object_or_404(teacher_list, pk=1)
    blog_reccommend = Blog.objects.filter(post_date__lt=date(2022,4,21))
    context = {
        'course_list': course_list,
        'course_detail': course_detail,
        'teacher_list': teacher_list,
        'teacher_detail': teacher_detail,
        'blog_reccommend': blog_reccommend,
    }
    return render(request, 'core/home.html', context)

def about_view(request):
    about = About.objects.all()
    fun_facts = FunFact.objects.all()
    about = get_object_or_404(about, pk=1)
    teacher_list = Teacher.objects.filter(id__lt=4)
    teacher_detail = get_object_or_404(teacher_list, pk=1)
    context = {
        'about': about,
        'head': 'About Us',
        'title': base_view(request),
        'fun_facts': fun_facts,
        'about': about,
        'teacher_list': teacher_list,
        'teacher_detail': teacher_detail,
    }
    return render(request, 'core/about.html', context)

def contact_view(request, li):
    title = {
            'name':'Contact Us',
            'content': """Do you have other questions? Don't worry, there aren't any dumb questions. Just fill out the form below and we'll get back to you as soon as possible.
            """
        }
    context = {
        'title': title,
    }
    return render(request, 'core/'+li, context)



# def blog_view(request, li, pk=1):
#     blog_list = Blog.objects.all()
#     blog_details = get_object_or_404(blog_list, pk=pk)
#     blog_reccommend = Blog.objects.filter(post_date__lt=date(2022,4,21))
#     context = {
#         'head': 'Our Blog',
#         'title': base_view(request),
#         'blog_details': blog_details,
#         'blog_list': blog_list,
#         'blog_reccommend': blog_reccommend,
#     }
#     return render(request, 'core/'+li , context)

# def course_view(request, li, pk=1):
#     course_list = Course.objects.all()
#     course_detail = get_object_or_404(course_list, pk=pk) 
#     school = course_detail.c_school   
#     req = course_detail.c_requirement.all()
#     req1 = req[:4]
#     req2 = req[4:]
#     course_reccommend = Course.objects.filter(Q(c_school=school)&~Q(id=pk))
#     context = {
#         'head': 'Our Courses',
#         'title': base_view(request),
#         'course_detail': course_detail,
#         'req': req,
#         'req1': req1,
#         'req2': req2,
#         'course_list': course_list,
#         'course_reccommend': course_reccommend
#     }
#     return render(request, 'core/'+li, context)

# def teacher_view(request, li, pk=1):
#     teacher_list = Teacher.objects.all()
#     teacher_detail = get_object_or_404(teacher_list, pk=pk)
#     courses = teacher_detail.t_courses.all() 
#     context = {
#         'head': 'Our Teachers',
#         'title': base_view(request),
#         'teacher_detail': teacher_detail,
#         'teacher_list': teacher_list,
#         'courses': courses,
#     }
#     return render(request, 'core/'+li, context)

# def event_view(request, li, pk=1):
#     event_list = Event.objects.all()
#     event_detail = get_object_or_404(event_list, pk=pk)
#     speakers = event_detail.e_speaker.all()
#     event_reccommend = Event.objects.filter(id__lt=4)
#     context = {
#         'head': 'Upcoming Events',
#         'title': base_view(request),
#         'event_detail': event_detail,
#         'event_list': event_list,
#         'event_reccommend': event_reccommend,
#         'speakers': speakers,
#     }
#     return render(request, 'core/'+li, context)

# def notice_view(request, li):
#     notice_list = Notice.objects.all()
#     notice_detail = get_object_or_404(notice_list, pk=1)
#     context = {
#         'head': 'Notice',
#         'title': base_view(request),
#         'notice_detail': notice_detail,
#         'notice_list': notice_list
#     }
#     return render(request, 'core/'+li, context)

# def research_view(request, li):
#     # research_detail = Research.objects.get(id=1)
#     research = Research.objects.all()
#     context = {
#         'head': 'Research',
#         'title': base_view(request),
#         'research': research,
#         # 'research_list': research_list
#     }
#     return render(request, 'core/'+li, context)

# def scholarship_view(request, li):
#     # scholarship_detail = Scholarship.objects.get(id=1)
#     scholarship = Scholarship.objects.all()
#     context = {
#         'head': 'Scholarship',
#         'title': base_view(request),
#         'scholarship': scholarship,
#         # 'scholarship_list': scholarship_list
#     }
#     return render(request, 'core/'+li, context)



"""------------------------------------------------------------

                    CLASS BASED VIEWS

------------------------------------------------------------"""

class CustomList(ListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        m = self.object_list.get(id=1)
        context['title'] = m.header_about
        return context

class CustomDetail(DetailView):
    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            context['blog_reccommend'] = Blog.objects.filter(post_date__lt=date(2022,4,21))
            context['event_reccommend'] = Event.objects.filter(id__lt=4)
            context['title'] = self.object.header_about            
            context['course_reccommend'] = Course.objects.filter(Q(c_school=self.object.c_school)&~Q(id=self.object.id))
        except AttributeError:
            pass
        return context

templates/core/base/footer.html
{% load static %}

<!-- footer -->
<footer>
  <!-- newsletter -->
  <div class="newsletter">
    <div class="container">
      <div class="row">
        <div class="col-md-9 ml-auto bg-primary py-5 newsletter-block">
          <h3 class="text-white">Subscribe Now</h3>
          <form action="#">
            <div class="input-wrapper">
              <input type="email" class="form-control border-0" id="newsletter" name="newsletter" placeholder="Enter Your Email...">
              <button type="submit" value="send" class="btn btn-primary">Join</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- footer content -->
  <div class="footer bg-footer section border-bottom">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-sm-8 mb-5 mb-lg-0">
          <!-- logo -->
          <a class="logo-footer" href="{% url 'user:home' %}"><img class="img-fluid mb-4" src="{% static 'images/logo.png'%}" alt="logo"></a>
          <ul class="list-unstyled">
            <li class="mb-2">23621 15 Mile Rd #C104, Clinton MI, 48035, New York, USA</li>
            <li class="mb-2">+1 (2) 345 6789</li>
            <li class="mb-2">+1 (2) 345 6789</li>
            <li class="mb-2">contact@yourdomain.com</li>
          </ul>
        </div>
        <!-- company -->
        <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
          <h4 class="text-white mb-5">COMPANY</h4>
          <ul class="list-unstyled">
            <li class="mb-3"><a class="text-color" href="{% url 'user:about' %}">About Us</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'user:teacher' %}">Our Teacher</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'user:contact' %}">Contact</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'user:blog' %}">Blog</a></li>
          </ul>
        </div>
        <!-- links -->
        <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
          <h4 class="text-white mb-5">LINKS</h4>
          <ul class="list-unstyled">
            <li class="mb-3"><a class="text-color" href="{% url 'user:course' %}">Courses</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'user:event' %}">Events</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'user:notice' %}">Notice</a></li>
            <li class="mb-3"><a class="text-color" href="{% url 'user:research' %}">Research</a></li>
          </ul>
        </div>
        <!-- support -->
        <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
          <h4 class="text-white mb-5">SUPPORT</h4>
          <ul class="list-unstyled">
            <li class="mb-3"><a class="text-color" href="#">Forums</a></li>
            <li class="mb-3"><a class="text-color" href="#">Documentation</a></li>
            <li class="mb-3"><a class="text-color" href="#">Language</a></li>
            <li class="mb-3"><a class="text-color" href="#">Release Status</a></li>
          </ul>
        </div>
        <!-- support -->
        <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
          <h4 class="text-white mb-5">RECOMMEND</h4>
          <ul class="list-unstyled">
            <li class="mb-3"><a class="text-color" href="#">WordPress</a></li>
            <li class="mb-3"><a class="text-color" href="#">LearnPress</a></li>
            <li class="mb-3"><a class="text-color" href="#">WooCommerce</a></li>
            <li class="mb-3"><a class="text-color" href="#">bbPress</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- copyright -->
  <div class="copyright py-4 bg-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-7 text-sm-left text-center">
          <p class="mb-0">Copyright
            <script>
              var CurrentYear = new Date().getFullYear()
              document.write(CurrentYear)
            </script> 
            © themefisher</p>
        </div>
        <div class="col-sm-5 text-sm-right text-center">
          <ul class="list-inline">
            <li class="list-inline-item"><a class="d-inline-block p-2" href="#"><i class="ti-facebook text-primary"></i></a></li>
            <li class="list-inline-item"><a class="d-inline-block p-2" href="#"><i class="ti-twitter-alt text-primary"></i></a></li>
            <li class="list-inline-item"><a class="d-inline-block p-2" href="#"><i class="ti-linkedin text-primary"></i></a></li>
            <li class="list-inline-item"><a class="d-inline-block p-2" href="#"><i class="ti-instagram text-primary"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- /footer -->

templates/core/base/header.html
{% load static %}
{% block header %}
<header class="fixed-top header">
  <!-- top header -->
  <div class="top-header py-2 bg-white">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-lg-4 text-center text-lg-left">
          <a class="text-color mr-3" href="callto:+443003030266"><strong>CALL</strong> +44 300 303 0266</a>
          <ul class="list-inline d-inline">
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-facebook"></i></a></li>
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-twitter-alt"></i></a></li>
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-linkedin"></i></a></li>
            <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i class="ti-instagram"></i></a></li>
          </ul>
        </div>
        <div class="col-lg-8 text-center text-lg-right">
          <ul class="list-inline">
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url 'user:notice' %}">notice</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url 'user:research' %}">research</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url 'user:scholarship' %}">SCHOLARSHIP</a></li>
            {% if user.is_authenticated %}
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="#" data-toggle="modal" data-target="#logoutModal">logout</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="{% url 'account:profile' %}">{{user}}</a></li>
            {% else %}
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="#" data-toggle="modal" data-target="#loginModal">log</a></li>
            <li class="list-inline-item"><a class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="#" data-toggle="modal" data-target="#signupModal">register</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- navbar -->
  <div class="navigation w-100">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark p-0">
        <a class="navbar-brand" href="{% url 'user:home' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
        <button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation"
          aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navigation">
          <ul class="navbar-nav ml-auto text-center">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:home' %}">Home</a>
            </li>
            <li class="nav-item @@about">
              <a class="nav-link" href="{% url 'user:about' %}">About</a>
            </li>
            <li class="nav-item @@courses">
              <a class="nav-link" href="{% url 'user:course' %}">COURSES</a>
            </li>
            <li class="nav-item @@events">
              <a class="nav-link" href="{% url 'user:event' %}">EVENTS</a>
            </li>
            <li class="nav-item @@blog">
              <a class="nav-link" href="{% url 'user:blog' %}">BLOG</a>
            </li>
            <li class="nav-item dropdown view">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Pages
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'user:teacher' %}">Teacher</a>
                <a class="dropdown-item" href="{% url 'user:teacher-single' 1 %}">Teacher Single</a>
                <a class="dropdown-item" href="{% url 'user:notice' %} ">Notice</a>
                <a class="dropdown-item" href="{% url 'user:notice-single' 1 %}">Notice Details</a>
                <a class="dropdown-item" href="{% url 'user:research' %}">Research</a>
                <a class="dropdown-item" href="{% url 'user:scholarship' %}">Scholarship</a>
                <a class="dropdown-item" href="{% url 'user:course-single' 1 %}">Course Details</a>
                <a class="dropdown-item" href="{% url 'user:event-single' 1 %}">Event Details</a>
                <a class="dropdown-item" href="{% url 'user:blog-single' 1 %}">Blog Details</a>
              </div>
            </li>
            <li class="nav-item @@contact">
              <a class="nav-link" href="{% url 'user:contact' %}">CONTACT</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item @@contact">
              <a class="nav-link" href="{% url 'backend:home' %}">BACKEND</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
  </div>
</header>
{% endblock header %}